### ISSUE TITLE
infinity.http: support multipart formdata content from string and stream

### ISSUE THREAD

**Issue by robert-rosendahl-greyhound-software** [Hervar77/infinity-js#4]
The infinity.http formdata items have a property `fileName` from which the contents for the formdata item is read. There are situations when this content is generated or read from a stream. It would be neat if the formdata items had two additional properties that function the same as the `fileName` property but provide the content from a string or a stream instead of from a file:
- `fileContent`: string with the content for this formdata item (instead of reading it from a file)
- `stream`: stream from which to read the content for this formdata item (instead of reading it from a file)

This is different from the property `fieldValue`, because field values are encoded differently and not appended as separate content items in the multipart request.

**Comment by Hervar77** [comment]
Fixed: The fileValue property supports now string or stream input value

**Comment by robert-rosendahl-greyhound-software** [comment]
If `fieldValue` is an `infinity.stream` object, then the content is added as a file. If a stream is used, then `fileName` will be used for the filename for the stream data (and the content will be read from the stream instead of a file).
